language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-25.0.2                # Build tools version
    - android-25                        # Target SDK version
    - extra-android-m2repository        # Support repo
    - sys-img-armeabi-v7a-android-18    # Emulator

jdk:
  - oraclejdk8

script:
#  - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy
#  - ./gradlew build
  - ./gradlew build coveralls

before_install:
 - chmod +x gradlew

env:
  global:
    - secure: "SONATYPE_NEXUS_USERNAME TODO"
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
    
before_script:
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  
  - ./gradlew connectedAndroidTest coveralls
